### ISSUE TITLE
能不能加上带调试符号的libc

### ISSUE THREAD

**Issue by junmoxiao** [matrix1001/welpwn#3]
rt

**Comment by matrix1001** [comment]
libc带的调试符号需要安装libc6-dbg，这个库是分离开的，不是libc本身。要加上这个，需要加上一堆文件，而且还有gdb指定调试符号的问题。目前建议自己编译libc，自带调试符号，以及源码。别的方便点的方法我还没想到。

**Comment by junmoxiao** [comment]
我的意思是编译个带-g的,这样就有main_arena这些符号了,只是没有源码而已,我自己就是这样编译的

**Comment by NyaMisty** [comment]
我测试了一下，并不是那么复杂。按照GDB官方文档：https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html
可以手动指定调试符号文件的位置
```ctx.debug(gdb_args=["-iex", "\"set debug-file-directory /mnt/d/UtilWorkspace/welpwn/PwnContext/libs/libc-2.23/64bit/dbg\""])```
用这样的方法即可加载，dbg目录下.build-id中存放了各个符号文件。
而对于自定义的libc则可以直接把符号文件放在同一个目录下面，然后也会自动加载。
要不考虑加个选项？

**Comment by matrix1001** [comment]
@NyaMisty 主要考虑到符号文件太大了， @junmoxiao 如果只是想要main_arena，可以看一下我的`heapinspect`项目，不需要符号就能解析堆。

**Comment by NyaMisty** [comment]
这样吧，要不我们在这个repo里面注明每个libs使用的包版本
然后我们再把调试符号单独放到一个repo里面（反正调试文件可以统一放到.build-id文件夹下面）
接着在我们这边加一个选项，可以指定debugfile directory

**Comment by NyaMisty** [comment]
而且都9102年了还在乎大小hhh一个文件就十MB加起来一个G都不够

**Comment by matrix1001** [comment]
可以的，准备另外起一个repo，用脚本的方式让用户自己下载好

**Comment by matrix1001** [comment]
@NyaMisty  https://github.com/matrix1001/glibc-all-in-one

**Comment by NyaMisty** [comment]
你这个不能解决问题啊。你得按照手册里面的那样，不然gdb加载不了调试符号

**Comment by matrix1001** [comment]
README和代码已更新，看看这个能不能解决问题。https://github.com/matrix1001/welpwn/commit/57e4cea2404864370b0feebb350f35c9baad7701

**Comment by NyaMisty** [comment]
阔以了，要求201806之后的版本，symbol-file -o的选项在201806才加上，对应版本号8.2.0左右，然鹅Ubuntu18.04带的是8.1.0，所以可以用1904的gdb或者用toolchain ppa的gdb
但是实际上正确的操作是在.so的同目录新建.debug目录）

**Comment by matrix1001** [comment]
@NyaMisty 原来还有.debug这个操作，所以我update了两个repo。
