### ISSUE TITLE
welpwn开启debug_remote_libc后pwndbg问题

### ISSUE THREAD

**Issue by sln-1550** [matrix1001/welpwn#6]
welpwn是个非常好的工具，最近发现一个问题，就是当我打开debug_remote_libc（ctx.debug_remote_libc=True）时pwndbg的有些命令就报错，比如bin和heap等，而且和libc的版本没有关系，我用本地的libc复制过来一样报错。
详细日志如下：
pwndbg> version
Gdb:      7.7.1
Python:   3.4.3 (default, Nov 28 2017, 16:44:58)  [GCC 4.8.4]
Pwndbg:   1.0.0 build: 2bc872c
Capstone: 4.0.1024
Unicorn:  1.0.1

pwndbg> bin
'bins': Prints out the contents of the tcachebins, fastbins, unsortedbin, smallbins, and largebins from the
    main_arena or the specified address.
Exception occured: bins: Could not convert Python object: None. (<class 'TypeError'>)
For more info invoke `set exception-verbose on` and rerun the command
pwndbg> set exception-verbose on
Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
pwndbg> bin
'bins': Prints out the contents of the tcachebins, fastbins, unsortedbin, smallbins, and largebins from the
    main_arena or the specified address.
Traceback (most recent call last):
  File "/home/test/tools/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/test/tools/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/test/tools/pwndbg/pwndbg/commands/__init__.py", line 208, in _OnlyWhenHeapIsInitialized
    if pwndbg.heap.current.is_initialized():
  File "/home/test/tools/pwndbg/pwndbg/heap/ptmalloc.py", line 526, in is_initialized
    return self.global_max_fast != 0
  File "/home/test/tools/pwndbg/pwndbg/heap/ptmalloc.py", line 177, in global_max_fast
    return pwndbg.memory.u(addr)
  File "/home/test/tools/pwndbg/pwndbg/memory.py", line 245, in u
    }[size](addr)
  File "/home/test/tools/pwndbg/pwndbg/memory.py", line 228, in u64
    return readtype(pwndbg.typeinfo.uint64, addr)
  File "/home/test/tools/pwndbg/pwndbg/memory.py", line 87, in readtype
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())
TypeError: Could not convert Python object: None.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome

**Comment by matrix1001** [comment]
这个应该是不是welpwn的问题，是pwndbg的，pwndbg的与堆相关的命令，只有在libc.so具有符号时才可以用，没有符号的libc.so无法被正确识别，你可以使用我的glibc-all-in-one里面的libc.so进行调试，这些都是带符号的。

**Comment by sln-1550** [comment]
> 这个应该是不是welpwn的问题，是pwndbg的，pwndbg的与堆相关的命令，只有在libc.so具有符号时才可以用，没有符号的libc.so无法被正确识别，你可以使用我的glibc-all-in-one里面的libc.so进行调试，这些都是带符号的。

glibc-all-in-one我不太清楚怎么用，我把下载过的libs/下libc-2.23.so复制过去，也是一样的，pwndbg使用堆的命令还是会报错。
我不明白的是，本地pwndbg可以运行堆命令，是不是说明本地的libc-2.23.so库有符号，那么为啥我用这个libc库文件，设置了debug_remote_libc=True就不行了呢？

**Comment by matrix1001** [comment]
```python
#https://github.com/matrix1001/welpwn
from PwnContext import *

try:
    from IPython import embed as ipy
except ImportError:
    print ('IPython not installed.')

if __name__ == '__main__':        
    context.terminal = ['tmux', 'splitw', '-h'] # uncomment this if you use tmux
    context.log_level = 'debug'
    # functions for quick script
    s       = lambda data               :ctx.send(str(data))        #in case that data is an int
    sa      = lambda delim,data         :ctx.sendafter(str(delim), str(data)) 
    sl      = lambda data               :ctx.sendline(str(data)) 
    sla     = lambda delim,data         :ctx.sendlineafter(str(delim), str(data)) 
    r       = lambda numb=4096          :ctx.recv(numb)
    ru      = lambda delims, drop=True  :ctx.recvuntil(delims, drop)
    irt     = lambda                    :ctx.interactive()
    rs      = lambda *args, **kwargs    :ctx.start(*args, **kwargs)
    dbg     = lambda gs='', **kwargs    :ctx.debug(gdbscript=gs, **kwargs)
    # misc functions
    uu32    = lambda data   :u32(data.ljust(4, '\0'))
    uu64    = lambda data   :u64(data.ljust(8, '\0'))
    leak    = lambda name,addr :log.success('{} = {:#x}'.format(name, addr))

    ctx.binary = './pwn'
    ctx.custom_lib_dir = '/root/share/project/glibc-all-in-one/libs/2.23-0ubuntu3_amd64/'
    ctx.debug_remote_libc = True

```
这是我的一个例子，请不要把libs下的东西复制到别的地方，直接用即可

**Comment by sln-1550** [comment]
嗯，经过测试，用ctx.custom_lib_dir的方法确实可以在pwndbg使用堆的命令，不过不知道为什么，总是和实际的运行的程序结果不一样，猜测可能是栈上有一些垃圾数据导致的。还有，那些堆的命令在最后的环境调试中几乎用不上，因此目前只用ctx.remote_libc的功能就很好了。
